feat: add an icon to the OSD popup
Bismuth-Forge/bismuth pull request #176
Opened 2021-11-08 18:16 UTC by verahawk

## Summary

Adds an icon to the OSD popup that appears when switching layouts.

## UI Changes

| Before                         | After                         |
| ------------------------------ | ----------------------------- |
| ![before](https://user-images.githubusercontent.com/28950897/140795856-86fb2b25-4349-478e-9ced-6fb83d90d945.jpg) | ![after](https://user-images.githubusercontent.com/28950897/140795901-63d54ae5-bbdb-4885-ae80-aee7dec66b5c.gif) |

## Test Plan

1. Reinstall Bismuth.
2. Restart KWin.
3. Switch between layouts.

## Related Issues

Closes #129

2021-11-08 18:26 UTC, verahawk commented
The icon is based on the [preferences-system-windows-effect-presentwindows](https://github.com/KDE/breeze-icons/blob/master/icons/applets/64/preferences-system-windows-effect-presentwindows.svg) icon from the Breeze theme.

2021-11-08 18:26 UTC, gikari requested changes
I don't like this icon: it is not monochrome and uses colors. The light version just inverses the dark one and looks not as good, as the icons in the Plasma popups (Mic mute, brightness and sound popups).

Checkout this: https://develop.kde.org/hig/style/icons/monochrome/status/

And due to above being an incomplete tutorial, I think you should check the SVG source of breeze Icons: https://invent.kde.org/frameworks/breeze-icons/-/tree/master/icons/status

2021-11-08 18:41 UTC, verahawk commented
I don't quite understand what do you mean by the monochrome part. It only uses the `#eff0f1` color and everything else is just a different opacity. It is done in the same way as in original Breeze icons that you have mentioned. For example, here is the volume/speaker icon:

```
<svg viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
    <style id="current-color-scheme" type="text/css">
        .ColorScheme-Text {
            color:#eff0f1;
        }
    </style>
    <g class="ColorScheme-Text" fill="currentColor">
        <path d="m14.324219 7.28125-.539063.8613281a4 4 0 0 1 1.214844 2.8574219 4 4 0 0 1 -1.210938 2.861328l.539063.863281a5 5 0 0 0 1.671875-3.724609 5 5 0 0 0 -1.675781-3.71875z"/>
        <path d="m13.865234 3.5371094-.24414.9765625a7 7 0 0 1 4.378906 6.4863281 7 7 0 0 1 -4.380859 6.478516l.24414.974609a8 8 0 0 0 5.136719-7.453125 8 8 0 0 0 -5.134766-7.4628906z" fill-opacity=".35"/>
        <path d="m3.0000005 8h2v6h-2z" fill-rule="evenodd"/>
        <path d="m6.0000005 14 5.0000005 5h.999999v-16h-1l-4.9999995 5z"/>
    </g>
</svg>
```

I agree that the light version doesn't look as good, but there is nothing we can do apart from shipping both the dark and light version and then somehow determining which one to display.

2021-11-09 22:28 UTC, verahawk commented
Do you mean something like this? (Yes, I know those are just 3 rectangles :D).

![osd](https://user-images.githubusercontent.com/28950897/141014080-5587da61-a564-41b4-87ab-83367d779752.png)

2021-11-09 22:45 UTC, gikari commented
> Do you mean something like this? (Yes, I know those are just 3 rectangles :D).
> 
> ![osd](https://user-images.githubusercontent.com/28950897/141014080-5587da61-a564-41b4-87ab-83367d779752.png)

Yep. It already looks better (actually, maybe even better, than what I want in my mind). Could you try to make something like this (awful Krita raster mockup, so in SVG in might look better):

![crude-mockup](https://user-images.githubusercontent.com/14205339/141017088-f1c24755-3198-4367-9159-dedb8d7e3453.png)

The color, that fills the window, should be the same as in your sound applet inactive stripe:

![Screenshot_20211110_014343](https://user-images.githubusercontent.com/14205339/141017466-cf0c1352-0c13-47c6-8589-2e24f6ce158d.png)

Not sure what will be the result

2021-11-09 23:02 UTC, verahawk commented
That filler color is just the main color with the opacity set to 0.35.

| ![light](https://user-images.githubusercontent.com/28950897/141019132-efa555ac-374d-4c1b-8d15-277b2647d000.png) | ![dark](https://user-images.githubusercontent.com/28950897/141019140-3e3bfa24-2256-45ef-af76-184c55162a93.png) |
| ------------------------------ | ----------------------------- |

2021-11-09 23:15 UTC, verahawk commented
Slightly different style:

![3](https://user-images.githubusercontent.com/28950897/141020344-06cf32fa-c737-4554-99fd-1b7fb05c2cde.png)

![4](https://user-images.githubusercontent.com/28950897/141020579-c22c2772-a7ae-4833-bf36-1ac5d00ce1b9.png)

2021-11-10 10:57 UTC, gikari commented
> ![4](https://user-images.githubusercontent.com/28950897/141020579-c22c2772-a7ae-4833-bf36-1ac5d00ce1b9.png)

I like this the most. Could you push it in git, so I will be possible to try it out?

2021-11-10 13:42 UTC, verahawk commented
What about custom icon for each layout? Or will it be too confusing?

![custom](https://user-images.githubusercontent.com/28950897/141122967-9004bae8-ab13-4215-a0b9-18e41a4eb014.gif)

2021-11-10 13:46 UTC, gikari commented
That's actually a very good idea! Go for it! 👍

2021-11-10 14:14 UTC, verahawk commented
I can create those icons, however adding them will require exposing a property that stores current layout to QML, and I don't know TS well enough to achieve this.

2021-11-10 14:18 UTC, gikari commented
> I can create those icons, however adding them will require exposing a property that stores current layout to QML, and I don't know TS well enough to achieve this.

Just create the icons then. I will create a code, that will use them later.

2021-11-10 18:23 UTC, gikari commented
I tested the current version of pop-up and it works and looks good. However, there is a bug, when you change the color scheme. When you do this, the color of the icon does not change, but if you trigger the pop up on another screen, it does.

Your SVG and CSS look fine. I need to investigate the issue.

2021-11-10 18:29 UTC, verahawk commented
Yes, restarting KWin will update it as well. I believe that's an upstream issue.

2021-11-11 21:47 UTC, gikari requested changes
I noticed, that the bug with colors could be worked around using the hack: setting the icon source in the show function:
```javascript
iconItem.source = "";
iconItem.source = "bismuth-osd";
```
This will not change the color of the already active popup, but will change it in the next one. I believe, that without this icon blending would be very annoying. So, could you please apply this here (with the in-code comment, that this is a workaround), and report the bug about colors shenanigans here and also to the upstream: https://bugs.kde.org

2021-11-11 21:47 UTC, gikari commented on src/kwinscript/ui/popup.qml
> +    property string tilingMode
As this is a general popup, it's better to provide the icon name as the second arg to the show function. This approach is used in the Plasma OSDs sources, as it's more flexible.

2021-11-11 23:02 UTC, verahawk commented on src/kwinscript/ui/popup.qml
> +    property string tilingMode
Ok. I've started to work on the backend as well. Just refactored the code that generates the OSD text. Tomorrow will implement the logic behind icons.

2021-11-12 13:11 UTC, verahawk commented on src/kwinscript/ui/popup.qml
> +    property string tilingMode
I have excluded this file from the PR as it's already implemented in #186.

2021-11-12 14:20 UTC, gikari approved these changes

2021-11-12 14:21 UTC, merged