wip: provide a backend for custom icons in the OSD popup
Bismuth-Forge/bismuth pull request #186
Opened 2021-11-12 01:09 UTC by verahawk

## Summary

Adds two optional parameters to the `showNotification` function:
- `text2` - right-aligned text, used to display the number of master windows in some layouts.
- `icon` - name of the icon, which should be displayed in the popup.

Required for #176

2021-11-12 14:26 UTC, gikari commented
> Required for #176

I merged the icons (with the different commit message), since they were fine, but then I saw this. In general, it's better to use "Depends on" notation, so that PR wouldn't get merged accidentally. (This is the notation KDE is using on their GitLab, btw).

2021-11-12 14:28 UTC, verahawk commented
It's ok, those commits are more or less independent anyway.

BTW, the cascade layout exists in the source code, but it's not present in the Window Layout list. Is it as it should be, or should I open a new issue?

2021-11-12 14:31 UTC, gikari commented
> It's ok, those commits are more or less independent anyway.
> 
> BTW, the cascade layout exists in the source code, but it's not present in the Window Layout list. Is it as it should be, or should I open a new issue?

Yeah, open an issue and address (if you could) this problem in a separate PR. No idea what is this layout and how stable it is, so I didn't touch it, just in case.

2021-11-13 16:01 UTC, gikari requested changes
![Screenshot_20211113_185107](https://user-images.githubusercontent.com/14205339/141650249-3386e4e3-e521-4085-bc96-de1477523bc4.png)

This is what I get. Not sure if it is the result, that is expected.

From the code, l could make a hypothesis, that this PR is not finished yet. Is it true?

2021-11-13 16:01 UTC, gikari commented on src/kwinscript/controller/index.ts
> +  showNotification(text: string, text2?: string, icon?: string): void;
In all similar functions, the icon and text2 should be swapped, as it's more probable, that we will use both icon and main text, while text2 is rare in all notifications.

2021-11-13 16:11 UTC, verahawk commented
> ![Screenshot_20211113_185107](https://user-images.githubusercontent.com/14205339/141650249-3386e4e3-e521-4085-bc96-de1477523bc4.png)
> 
> This is what I get. Not sure if it is the result, that is expected.
> 
> From the code, l could make a hypothesis, that this PR is not finished yet. Is it true?

Strange, it works for me. Make sure to remove build directory and restart KWin.

2021-11-13 16:14 UTC, verahawk commented
![example](https://user-images.githubusercontent.com/28950897/141650949-da9c33b8-340b-4cb4-9345-c954dbf4328b.png)

2021-11-13 16:18 UTC, gikari commented
> Strange, it works for me. Make sure to remove the build directory prior to compilation and restart KWin afterwards.

1. I did a [change](https://github.com/Bismuth-Forge/bismuth/commit/9996263b3b598279a7b6bd1c2e16f868f04c3bdd), that makes the clean build unnecessary. You should rebase. If you need to do a clean build - it's a bug in the build process in the most cases.
2. I don't see any change in the diff, that uses new show function signature. That's why on my screenshot, the default bismuth icon is used, and the old text is displayed.

2021-11-13 16:33 UTC, verahawk commented
> 2. I don't see any change in the diff, that uses new show function signature.

What do you mean by signature? Sorry, I am new to TS.
I extended old `showNotification` function with two new parameters. You can see it called [here](https://github.com/Bismuth-Forge/bismuth/blob/3224e7bb9d9d500f0a4c9430f3f0bba77d45aaf0/src/kwinscript/ui/popup.qml#L17).

2021-11-13 16:48 UTC, gikari commented
I think I found a bug in the build system, that does not update my code. I will fix it and will review your changes.

2021-11-13 17:32 UTC, gikari requested changes
Looks incredibly good! :+1: Just a couple of nitpicks, and you are good to go.

2021-11-13 17:32 UTC, gikari commented on src/kwinscript/ui/popup.qml
> +        messageIcon.source = icon || "bismuth"; // Fallback to the default icon when undefined
Not sure the default logo is a good choice. I think the tiling layout one is better (although, for some notifications we should definitely create icons ("Rotation not applicable", "No master Area"), but not in this PR of course).

2021-11-13 17:32 UTC, gikari commented on src/kwinscript/ui/popup.qml
> +            Layout.rightMargin: PlasmaCore.Units.smallSpacing * 2
I think this label also need a minimal width, so that the text in the near one does not jump, when you change the master size (like in the default Plasma OSD, in which the elements are staying inside, when you have e.g.  5% of brightness or sound volume).

2021-11-13 17:32 UTC, gikari commented on src/kwinscript/engine/layout/index.ts
> +  readonly hint?: string;
You may create some JSDoc comments here for the new fields.

2021-11-13 17:37 UTC, verahawk commented on src/kwinscript/ui/popup.qml
> +        messageIcon.source = icon || "bismuth"; // Fallback to the default icon when undefined
Yeah, it's just a last resort fallback.

2021-11-13 17:44 UTC, gikari commented
I made a fix for the CI, you should rebase.

2021-11-13 18:11 UTC, gikari commented on src/kwinscript/ui/popup.qml
> +        messageIcon.source = icon || "bismuth"; // Fallback to the default icon when undefined
Ok

2021-11-13 18:20 UTC, gikari commented on src/kwinscript/engine/layout/index.ts
> +   */
This is an incorrect syntax. See this [example](https://github.com/Bismuth-Forge/bismuth/blob/3d1233ea6f6a452f5220d831f92076f336eac35d/src/kwinscript/extern/kwin.d.ts#L83) for how to document these things.

2021-11-13 18:21 UTC, verahawk commented on src/kwinscript/engine/layout/index.ts
> +   */
Oh, ok.

2021-11-13 18:43 UTC, verahawk commented on src/kwinscript/engine/layout/index.ts
> +   */
Not sure, if I got it right...

2021-11-13 18:44 UTC, gikari approved these changes

2021-11-13 18:49 UTC, verahawk commented
Should I squash them all?

2021-11-13 18:50 UTC, gikari commented
> Should I squash them all?

I'll do it for you. No problem.

2021-11-13 18:52 UTC, merged

2021-11-13 19:13 UTC, gikari commented
Good job! :+1: