Adding bismuth into official fedora repository and update fedora installation guide.
Bismuth-Forge/bismuth pull request #353
Opened 2022-05-01 12:23 UTC by thunderbirdtr

Hi,

I started the process of package review in Fedora for bismuth so we can directly with "dnf " without adding extra repository.  Once package review is complete I would like to see merge this request and replace current readme with official way of installation for Fedora. 

Latest version copr repo : https://copr.fedorainfracloud.org/coprs/g/kdesig/bismuth/
(It will be not update once package pushed to fedora, it is here for testing)

Fedora package review link  : https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2080701

Thank you.

2022-06-15 09:58 UTC, gikari requested changes
Before the review is finished on Fedora side: you need to fix your commit name, so that it conforms to [Conventional Commits](/https://www.conventionalcommits.org/en/v1.0.0/).

2022-08-08 00:35 UTC, eclipseo commented
Note that the building is done, we just need it to move to stable repo.

2022-08-08 10:14 UTC, onuralpszr commented
@gikari pacakge review and build complete. I also edited commit message as well. 

We have bismuth in fedora :fireworks: 

Fedora 37 (Rawhide) already pushed to stable and for F36/F35 It needs testing/karma once they complete we will have it in all 3 different version as well.  

https://bodhi.fedoraproject.org/updates/FEDORA-2022-5aa27e6826
https://bodhi.fedoraproject.org/updates/FEDORA-2022-58d2ec9689

2022-08-08 10:36 UTC, onuralpszr reviewed
commit change complete.

2022-08-08 11:09 UTC, gikari commented
This will be merged once it lands on the latest Fedora release (36 or 37, once it's released).

2022-08-08 11:09 UTC, gikari approved these changes

2022-08-10 05:47 UTC, onuralpszr commented
@gikari,  bismuth rpm package pushed to Fedora 36 (stable) and Fedora 37 (rawhide)  repositories. We can merge it. 

Thank you.

2022-08-10 10:22 UTC, merged