fix windows not tiling after changing desktops or activities
Bismuth-Forge/bismuth pull request #377
Opened 2022-06-21 15:37 UTC by benemorius

## Summary

Currently the signals we're getting from kwin aren't causing us to retile windows when they're moved between desktops or activities. This PR connects the signals so we trigger a retile when either the desktop or activity is changed.

## Test Plan

* move a window from the current desktop/activity to a different one
* switch to that desktop/activity
* without this fix, the desktop/activity is not tiled to reflect the moved window

## Related Issues

Closes #363

2022-06-21 20:18 UTC, gikari requested changes
Nice catch. It's very strange, that those signals were not previously connected.

2022-06-21 20:18 UTC, gikari commented on src/kwinscript/driver/index.ts
> +    this.connect(this.kwinApi.workspace.currentActivityChanged, () =>
Those signals belong to the entire workspace and not a window. Therefore, the connections should be placed inside the `bindEvents` function.

2022-06-21 20:18 UTC, gikari commented on src/kwinscript/extern/kwin.d.ts
> +     * Emitted when the desktop changes. One signal is sent per each window.
The same questions.

2022-06-21 20:18 UTC, gikari commented on src/kwinscript/driver/index.ts
> +    this.connect(this.kwinApi.workspace.currentDesktopChanged, () =>
Same.

2022-06-22 02:22 UTC, benemorius commented
> Those signals belong to the entire workspace and not a window. Therefore, the connections should be placed inside the bindEvents function.

That! That explains the event-per-window behavior. I was sure that was buggy behavior, that's why I documented it, but I was looking for the problem in kwin.

I moved it out of the window events and of course now I'm not getting those duplicate events anymore. I pushed an update.

I'm assuming we used to be triggering arranging incidentally from some other signal that kwin used to send and doesn't anymore and that's why these missing signals weren't being noticed. Although I get the same behavior with kwin 5.21.4 so I dunno.

2022-06-23 17:41 UTC, gikari approved these changes

2022-06-23 18:06 UTC, merged